export const colors = {
  stationBlue: 'var(--appstore-accent)',
  blueGray: 'var(--appstore-surface)',
  blueGray100: 'var(--appstore-text)',
  blueGray40: 'var(--appstore-surface-raised)',
  blueGray30: 'var(--appstore-surface)',
  blueGray10: 'var(--appstore-surface-subtle)',
  hoverBlue: 'var(--appstore-hover)',
  blueGlowing: 'var(--appstore-focus)',
  gray: 'var(--appstore-text-muted)',
  dividerColor: 'var(--appstore-border)',
  darkGray: 'var(--appstore-text-muted)',
  white: 'var(--appstore-input)',
  activeSuggestion: 'var(--appstore-active)',
  buttonBorder: 'var(--appstore-border-strong)',
};
