name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    ## This is used to not re-run the build if only thoses files have changed
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
jobs:
  Linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "24"
          cache: "yarn"
      # - name: Configure Node
      #   run: |
      #     yarn set version stable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
        
  MacOs:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "24"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Tests
        run: yarn test

  Windows:
    runs-on: windows-2025
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "24"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Tests
        run: yarn run test
